### ISSUE TITLE
Question about test data

### ISSUE THREAD

**Issue by tppd67421** [lanavasilieva/Syberry-Academy-Test-Task-For-Developers#4]
![image](https://user-images.githubusercontent.com/25455143/96354871-212b3600-10e4-11eb-9317-218baf6613bd.png)
Why we have "Abb" in `intervalConstruction` (`examples.md`)?
3deg between Cb and A (C, B, A).
4sem between Cb and Ab. From Cb to B - 1sem, from B to A - 2sem, from A to G - 2sem. So, we have 5sem and get note name G (or Abb). We should get less 1sem and we can write note name G# (or Ab).
So, in deg we get note name A. And in sem between G# and Ab we should select Ab.

My answer Ab. Where did I go wrong?

**Comment by DuIIDa** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44843835/96364814-2b315100-1145-11eb-95f5-ecdd57dc521c.png)
Тот же вопрос, почему Abb в intervalConstruction( examples.md)?
M3 - Большая третья - 4 полутона, 3 градуса
Получаем ноту A, от Cb до A 4 полутона(от Cb до B = 2 и от B до A = 2) M3 имеет 4 полутона и получаем 4-4=0 и ничего лишнего не остается, получаем А в итоге.
Все тесты функция проходит кроме этой.

**Comment by gubka-bob** [comment]
Между В и С - 1 полутон. От Cb до B - 0 полутонов, от B до A - 2 полутона: B-Bb и A#-A. По итогу получаем 2 полутона, а нужно 4, т.е. не хватает 2 полутонов, поэтому добавляем к А две bb и получаем Abb.

**Comment by screamcol** [comment]
> 
> 
> Между В и С - 1 полутон. От Cb до B - 0 полутонов, от B до A - 2 полутона: B-Bb и A#-A. По итогу получаем 2 полутона, а нужно 4, т.е. не хватает 2 полутонов, поэтому добавляем к А две bb и получаем Abb.

Почему вы считаете, что между Cb и B - 0 полутонов?
Возьмем ноты из теории, которые нам предоставлены:
Here one dash means one semitone:
C--D--E-F--G--A--B-C 

Да, между B и C 1 семитон. Но также между E и F тоже 1 семитон. Почему например из инпута тестового с параметрами
['m2', 'Fb', 'asc'] мы получаем не Gb а Gbb? Наверное потому, что E#/Fb - F - F#/Gb - G
Считаем: E#/Fb -> F это первый семитон, F ->F#/Gb это второй семитон и F#/Gb -> G это третий семитон. Получаем 3 семитона - 2 и получаем Gbb. Здесь все верно либо наоборот здесь не верно. Почему в варианте инпута ['M3', 'Cb', 'dsc'] получается Abb не ясно. Возможно там ошибка.

**Comment by DuIIDa** [comment]
> Между В и С - 1 полутон. От Cb до B - 0 полутонов, от B до A - 2 полутона: B-Bb и A # -A. По итогу получаем 2 полутона, а нужно 4, т.е. не хватает 2 полутонов, поэтому добавляем к А две bb и получаем Abb.

Тут верно сказано, я разобрался)

**Comment by screamcol** [comment]
> 
> 
> > Между В и С - 1 полутон. От Cb до B - 0 полутонов, от B до A - 2 полутона: B-Bb и A # -A. По итогу получаем 2 полутона, а нужно 4, т.е. не хватает 2 полутонов, поэтому добавляем к А две bb и получаем Abb.
> 
> Тут верно сказано, я разобрался)

ну по этому логике получается, что если между E и F имеется 1 полутон, то Fb - F тоже 0  полутонов. Но это не так. Или я чего-то не понимаю?

**Comment by DuIIDa** [comment]
> > > Между В и С - 1 полутон. От Cb до B - 0 полутонов, от B до A - 2 полутона: B-Bb и A # -A. По итогу получаем 2 полутона, а нужно 4, т.е. не хватает 2 полутонов, поэтому добавляем к А две bb и получаем Abb.
> > 
> > 
> > Тут верно сказано, я разобрался)
> 
> ну по этому логике получается, что если между E и F имеется 1 полутон, то Fb - F тоже 0 полутонов. Но это не так. Или я чего-то не понимаю?

['M3', 'Cb', 'dsc'] при этой задаче мы идем в обратную сторону(dsc), благодаря чему B-Cb компенсируют друг друга и получается 0

**Comment by gubka-bob** [comment]
> > Между В и С - 1 полутон. От Cb до B - 0 полутонов, от B до A - 2 полутона: B-Bb и A#-A. По итогу получаем 2 полутона, а нужно 4, т.е. не хватает 2 полутонов, поэтому добавляем к А две bb и получаем Abb.
> 
> Почему вы считаете, что между Cb и B - 0 полутонов?
> Возьмем ноты из теории, которые нам предоставлены:
> Here one dash means one semitone:
> C--D--E-F--G--A--B-C
> 
> Да, между B и C 1 семитон. Но также между E и F тоже 1 семитон. Почему например из инпута тестового с параметрами
> ['m2', 'Fb', 'asc'] мы получаем не Gb а Gbb? Наверное потому, что E#/Fb - F - F#/Gb - G
> Считаем: E#/Fb -> F это первый семитон, F ->F#/Gb это второй семитон и F#/Gb -> G это третий семитон. Получаем 3 семитона - 2 и получаем Gbb. Здесь все верно либо наоборот здесь не верно. Почему в варианте инпута ['M3', 'Cb', 'dsc'] получается Abb не ясно. Возможно там ошибка.

Я ни разу не музыкант и не знаю, правильно ли написано в задании или нет:) Я считаю семитоны так: E-E# семитон, E#-Fb не семитон, Fb-F семитон. В примере ['m2', 'Fb', 'asc']: m2 (1 семитон и 2 ноты), ноты F(1) G(2), семитоны FbF(1), FF#(2), GbG(3) - то есть 3 семитона. По условию у интервала m2 1 семитон и 2 ноты. Получается, что итоговая нота это G, остается разобраться с семитонами. Их есть 3, а нужен 1, поэтому к ноте G добавляем 2 b и получаем Gbb.

**Comment by tppd67421** [comment]
> > > > Между В и С - 1 полутон. От Cb до B - 0 полутонов, от B до A - 2 полутона: B-Bb и A # -A. По итогу получаем 2 полутона, а нужно 4, т.е. не хватает 2 полутонов, поэтому добавляем к А две bb и получаем Abb.
> > > 
> > > 
> > > Тут верно сказано, я разобрался)
> > 
> > 
> > ну по этому логике получается, что если между E и F имеется 1 полутон, то Fb - F тоже 0 полутонов. Но это не так. Или я чего-то не понимаю?
> 
> ['M3', 'Cb', 'dsc'] при этой задаче мы идем в обратную сторону(dsc), благодаря чему B-Cb компенсируют друг друга и получается 0

Промежуток между нотами равен нулю по причине того, что мы идем вниз? Или я что-то не полностью понял?

**Comment by tppd67421** [comment]
123

**Comment by tppd67421** [comment]
Если рассчитывать sem и deg между нотами взяв за исходное значение чистую ноту (без диеза и бемоля), то мой алгоритм, находящийся в голове, прошел все тесты на листике.

В качестве примера возьму ту ситуацию, которая вызвала вопрос.
`3deg between Cb and A (C, B, A).`
Ну тут все понятно, без изменений. Но дальше интереснее. Наша нота Cb и мы берем ноту C (b в уме, как нас учили в школе). Считаем 4sem от С. Попадаем на G#/Ab. Попадаем ровно. Достаем из ума наш b и получаем Abb.

В итоге все получается если брать для расчета расстояния deg и sem "чистую ноту", а потом прибавлять то, что мы прятали в уме. Но

В файле `intervals.md` есть пример идущий по порядку вторым (P5 from Ab). Мы рассчитываем deg ноты Ab при помощи `ignoring 'b'`. Окей, мы все, я думаю, так и делали. Дальше рассчитываем sem от Ab (!). Тут же мы диез и бемоль не откидываем. Хорошо, в данном случае это не проблема, так как ноту Ab мы можем без труда найти в нашей "табличке":

`C C#/Db D D#/Eb E F F#/Gb G G#/Ab A A#/Bb B`

Последний пример с нотой Fb самый интересный, так как данная нота в "табличке" не фигурирует. И это единственный пример с нотой, которая в таблице не фигурирует (а так как ноты, которых в таблице нет, фигурируют в `examples.md`, то я, думаю как и все остальные, цепляюсь за этот пример).

Итак, deg считаем без проблем. С sem будет поинтереснее. `from Fb to G is 3 semitones`. Смотрим на другую таблицу:

`Here one dash means one semitone:
C--D--E-F--G--A--B-C`

Видим, что между F и G находится 2sem. Если между Fb и G 3sem (исходя из примера), то можно предположить, что между Fb и F 1sem. Получается можно (ошибочно?) предположить, что между нотами E и F находится нота E#/Fb. И между E и E# 1sem, между Fb и F 1sem и в то же время между E и F 1sem. 

Получается мы можем прибавить к абсолютно любой ноте диез или бемоль и считать за один полутон расстояние между этой новой нотой и основной?

Вооружившись своей логикой иду считать 4sem от ноты Cb (мой вопрос, послуживший созданию данной проблемы). Итак, смело размещая ноту Cb и считаю 1sem до ноты B. Дохожу до ноты G от ноты B за 4sem, что суммарно выливается в 5sem. Много, для данного промежутка необходимо 4sem. Тогда добавляю к ноте G диез, что идентично ноте A с бемолем (Ab).

Исходя из логики, которая представлена в примере, данная задача решается неверно. Но исходя из моей логики (прячем диез и бемоль в уме и добавляем потом), все получается. Тем не менее хотелось бы услышать официальный комментарий от @lanavasilieva, @SyberryAcademy или кого-либо еще чтобы исключить все недоразумения, так как однозначной интерпретации данного тестового у меня нет

**Comment by SyberryAcademy** [comment]
Тестовые данные в таблице корректные (я на всякий случай проверила еще раз).
@gubka-bob, когда будете отправлять свое тестовое нам, прилепите этот скрин, пожалуйста, к письму.

Комментировать решения я не буду, чтобы не дать кому-то из вас преимущество перед теми, кто не видел этот тред.

**Comment by valeriaKypreeva** [comment]
@lanavasilieva , Можно уточнить, если: 
A file must contain only two functions: intervalContruction() and intervalIdentification(),
то получается в классе нельзя объявлять какие-то свои данные(объявлять их уже непосредственно в функциях тогда, а не в классе), нельзя делать свои дополнительные функции(будет только две эти и всё)??

И можно ли к этим двум функциям добавить throws Exception в сигнатуру? (Java)

**Comment by VladislavKokosh** [comment]
@SyberryAcademy возник вопрос с тестовыми данными ['P4', 'G#', 'dsc']. По чистому G идем на 4 градуса и попадаем в D, от G# до D считаем семитоны (G#, G,Gb, F#, F, E, Eb, D#, D в этом промежутке интервалов),  я насчитываю, как минимум 5(от G до F - 2, от F до E - 1, от E до D - 2), у вас в тестовых данных выходит 4 и вы добавляете шарп к D, как в этом промежутке интервалов насчитывается только 4 семитона?

**Comment by VladislavKokosh** [comment]
![image](https://user-images.githubusercontent.com/60326279/96637000-bd447f80-1326-11eb-8be1-f44de823d387.png)
Мою теорию подтверждает ваш пример, где от D до G 5 семитонов

**Comment by gubka-bob** [comment]
> ![image](https://user-images.githubusercontent.com/60326279/96637000-bd447f80-1326-11eb-8be1-f44de823d387.png)
> Мою теорию подтверждает ваш пример, где от D до G 5 семитонов

Я при обратном порядке использовал обратную логику: если количество подсчитанных полутонов больше положенного, до добавлял #, если меньше b
['P4', 'G#', 'dsc'] - здесь 6 интервалов: G#G, GGb, F#F, FE, EEb, D#D. У P4 по условию 5 полутонов. 6-5=1, добавляем при обратном порядке # и получаем D#.

Моя логика, возможно, неправильная, но тесты проходят:)

**Comment by iamkoks** [comment]
@gubka-bob у меня двое тестовых данных по коду не проходят, психую ужасно уже :D 
буду заливать, как есть

**Comment by SyberryAcademy** [comment]
> @lanavasilieva , Можно уточнить, если:
> A file must contain only two functions: intervalContruction() and intervalIdentification(),
> то получается в классе нельзя объявлять какие-то свои данные(объявлять их уже непосредственно в функциях тогда, а не в классе), нельзя делать свои дополнительные функции(будет только две эти и всё)??
> 
> И можно ли к этим двум функциям добавить throws Exception в сигнатуру? (Java)

@valeriaKypreeva Вы абсолютно правы! убрала ONLY из требований. в файле должны быть минимум две указанные функции, на остальное ограничений нет.

**Comment by SyberryAcademy** [comment]
@iamkoks тестовые данные корректные : )
берегите нервы! а то напишут на девбай потом "белорусский разработчик подал в суд на задание за моральный ущерб" :)
Вы запутались в том, как считать "asc" и "dsc".

**Comment by VladislavKokosh** [comment]
> @iamkoks тестовые данные корректные : )
> берегите нервы! а то напишут на девбай потом "белорусский разработчик подал в суд на задание за моральный ущерб" :)
> Вы запутались в том, как считать "asc" и "dsc".

с суда в шепот :D 
прошу прощения, я разобрался :))

**Comment by SyberryAcademy** [comment]
@iamkoks Ждем ссылку на репо! : )

**Comment by VladislavKokosh** [comment]
> @iamkoks Ждем ссылку на репо! : )

проверяйте ;)

**Comment by lanavasilieva** [comment]
Закрываю issue.
