### ISSUE TITLE
Migrate from Java 15

### ISSUE THREAD

**Issue by nopilei** [lanavasilieva/Syberry-Academy-Test-Task-For-Developers#7]
Я выполнил задание на Java 15 и отправил его 2 дня назад. Сегодня решил проверить репозиторий и обнаружил, что теперь в требованиях Java 14 и старше. Я проверил, например, на Java 8 код не работает из-за немного других требований к синтаксису. Сделать комит с изменениями или оставить все как есть, как поступить?

**Comment by SyberryAcademy** [comment]
@truekorsar 
Наш Grading Script проверяет задания написанные только на джаве 14 и старше. К сожалению, скрипт мы написали до 15 сентября (день выхода джавы 15)! Простите за неудобства! 
Да, пожалуйста, обновите код и напишите нам имейл, что код обновлен.
